# vim:ft=kitty

## name: Atelier Sulphurpool Dark
## author: Bram de Haan (https://github.com/atelierbram)
## license: MIT
## upstream: https://github.com/atelierbram/AtelierSchemes-kitty/blob/main/themes/atelier-sulphurpool-dark.conf
## blurb: Purple-ish otherworldly colorscheme


#: The basic colors

foreground #e6e6e6
background #000000
selection_foreground #e6e6e6
selection_background #444444


#: Cursor colors

cursor #e6e6e6
cursor_text_color #000000


#: URL underline color when hovering with mouse

url_color #00ffff


#: kitty window border colors and terminal bell colors

active_border_color #e6e6e6
inactive_border_color #000000
bell_border_color #ff0000
visual_bell_color #ff0000


#: OS Window titlebar colors

wayland_titlebar_color #000000
macos_titlebar_color #000000


#: Tab bar colors

active_tab_foreground #e6e6e6
active_tab_background #000000
inactive_tab_foreground #aaaaaa
inactive_tab_background #000000
tab_bar_background #000000
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)

mark1_foreground #000000
mark1_background #e6e6e6
mark2_foreground #000000
mark2_background #ffff00
mark3_foreground #000000
mark3_background #00ffff


#: The basic 16 colors

#: black
color0 #000000
color8 #7f7f7f

#: red
color1 #ff0000
color9 #ff5555

#: green
color2 #00ff00
color10 #55ff55

#: yellow
color3 #ffff00
color11 #ffff55

#: blue
color4 #00aaff
color12 #55ccff

#: magenta
color5 #ff00ff
color13 #ff55ff

#: cyan
color6 #00ffff
color14 #55ffff

#: white
color7 #e6e6e6
color15 #e6e6e6
