# BEGIN_KITTY_THEME
# Atelier Sulphurpool Dark
include current-theme.conf
# END_KITTY_THEME

font_size 10

shell_integration disabled


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font'
bold_font        family='JetBrainsMono Nerd Font'
italic_font      family='JetBrainsMono Nerd Font'
bold_italic_font family='JetBrainsMono Nerd Font'
# END_KITTY_FONTS

symbol_map U+1F000-U+1FAFF Noto Color Emoji
symbol_map U+2600-U+26FF Noto Color Emoji
