# BEGIN_KITTY_THEME
# Atelier Sulphurpool Dark
include current-theme.conf
# END_KITTY_THEME

font_size 10

shell_integration enabled


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' style='regular'
bold_font        family='JetBrainsMono Nerd Font' style='regular'
italic_font      family='JetBrainsMono Nerd Font' style='Light Italic'
bold_italic_font family='JetBrainsMono Nerd Font' style='Italic'
# END_KITTY_FONTS

symbol_map U+1F000-U+1FAFF Noto Color Emoji
symbol_map U+2600-U+26FF Noto Color Emoji
map ctrl+shift+enter none
map ctrl+shift+n new_os_window_with_cwd
