general {
  lock_cmd = /usr/bin/hyprlock
  before_sleep_cmd = /usr/bin/hyprlock
  after_sleep_cmd = hyprctl dispatch dpms on
}

# Bloquear tras 10 min de inactividad
listener {
  timeout = 6000
  on-timeout = /usr/bin/hyprlock
}

# Suspender tras 20 min de inactividad
listener {
  timeout = 1200
  on-timeout = systemctl suspend
}
